### ISSUE TITLE
Minitutorial

### ISSUE THREAD

**Issue by DaserTwo** [DaserTwo/EcoFarm2D#2]
First msgs should describe how to play the game.

**Comment by spaanko** [comment]
Dodany mini tutorial.  narazie chodzenie skakanie oraz interakcja ze slotami

**Comment by DaserTwo** [comment]
No information about tools, we do not support W or S keys.

**Comment by spaanko** [comment]
Fixed. Removed W and S added keys 0-9 and tab for tools.
